title:       "Operating Systems 2021-1 (OS211)"
version:     "005---10-Mar-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Hendrico Kristiawan"
address:          "Bekasi"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlcontact:       "TBS"
keywords:         "jekyll, testing"
github:           [metadata]
